name: CI/CD Pipeline for FastAPI Microservice

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: |
          {
            "type": "service_account",
            "project_id": "sunny-truth-444203-c0",
            "private_key_id": "4a6e75ca77f4d914ffb57866e717be0fc9e5342a",
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxTm78xy5I+0Ib\n+ZvdQfbrOqFbyFC4rHE22R3Y5sC0q0IAmouI8uIQYpSAHXif3Th7MTnsPCrnUJh6\nmbuW4wlSdPG3lepazn1+3/R9WQmyW+XXbioQFNO9cjsUqq5TgR2PzIAEel+825PY\nIsic/fdQz06X9jTwnUcaXy/PPw007i4ZJOYsVANzjBNu+DJ3DoEW3DfbzVatGBnb\n/vqhFlBlpo6L1LI2VMDmOZS8s9mg0LmBHRvc8QSzvri4iDV9AihnzK6kPmpmC1Vb\nL2/EWN78Hl3dxOrvJ6oHc86+wnkkupR/EFOl6zDSm6YztVSm8LWbRiVyY4PBz/by\nK24i22pvAgMBAAECggEAGZR2QLO/wrm1JPITAY3VwMQZqXMx6iK+xqn2O2e3H5mh\nkRK61Mwtvy1pvT4DPBUfY+6LK8DWc77V8MIjJTamDqZehRz0zZsC0f4feMISuw+1\nDiqPmPhYP/mt+mJReiyjhi57vammDEolf0YtaTDesGLoNNZJdvlJ280lyaGQFzWT\n/BPOpPsFzZRopnXpCO/lGQsU3nXYCwhBLaqdPpE23h+qi3RyA5UKffzVLltiRaQT\n4T5WYxGdSCfojjZqMQZj4jBKAOcal87LnGqNPoxESGBywrJ81EsSaWsMK1m2J1f4\nyZJPjVG61gEoEJSy46twLyMUy+ixVKhBp6b/EIdckQKBgQDl4H63NFZXAaWnwBIE\ntPmjlo6vufHgN91nGguv07TkoQ88DP8qzKQhJn/EJB1Uc9hISaT/oLb9qwcMSrUU\nWpO3GrLO0GwI+lTZz+nRmY704ItQgXNRlQ56D9sOUSXSx7eMifzDY5saDlEJzc0M\nRsL+qFXTw6APEO0Se71MrMHTVwKBgQDFdJK5P+mrq6WKjY3KXh7GIvfk2gGgL0/d\nntbBxIOv2p2/hpP3V7zAe4pmne8DbbnUTgRtGWFb3kH7z7shJlCGyJabREqAbLsu\nspvBLFhkF9F1MRJ/otOAsYM17POoQdMTnLnbz16EGvXxjtoi8nyCN5hoBTPk9s6F\n6sGqqpaKqQKBgQCUWZqtNLN7lu6HIab/LqPkdKdEtKVp4+OYQ/DC2cdlvKMOR/zs\nbACH/EZ8GCptdA1iKVS4O8mcTyFPR28w4XtusWYvncX6zUKxBkKJJ6ZgVgDSRZhc\nT+t1zoG57ZiRPJ4xrmNW3RMdb5vQzeXERG5W1d/9t8O1tWCpiv2RW/QCJQKBgCyg\neDjeNRXTqYpzC8TdGN93L8fNbeiiSM6yA5+vpoOsSVLsO6z/a22lflZLA6YmuoU9\nTMrLnbGBvjAHdye63SBZXZCiEqSL7pJTU9iJCUE2EOUHvkKSrnK7rAgYEcnJdsdL\n+MWxTI9W+Jcrzilv3KwhnJSF+ICbN3oU4MiN3ZBhAoGALb7FR3o2QdxeUuIpeKqF\nrVVoi4Zo5pkfZjZDx9/3/LxyGea9/Wp/z/RolLi7buiBvLdhuOyeeekbB8h59YFn\npQgPNtPmHpVXQWwFK5r/gYKRmX/X2eUzXxvqEmzHjSmtPeQ+yk7CGEoBXTavHnxE\nHQhNRYNmcAy2nXJgfjvjF8I=\n-----END PRIVATE KEY-----\n",
            "client_email": "github-actions-deployer@sunny-truth-444203-c0.iam.gserviceaccount.com",
            "client_id": "113434002897615605598",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/github-actions-deployer%40sunny-truth-444203-c0.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }
        project_id: sunny-truth-444203-c0
        export_default_credentials: true
        
    - name: Verify Authentication
      run: gcloud auth list
        
    - name: Deploy to Google App Engine
      run: gcloud app deploy --quiet
